### ISSUE TITLE
Botania mana pool cart

### ISSUE THREAD

**Issue by Prospector** [BrassGoggledCoders/MoarCarts#12]
Had this thought. Seems like it might be kinda difficult though... especially trying to get a mana spreader to work with it. Might also break some balance if a mana a pool could be moved so easily.

**Comment by SkySom** [comment]
Botania already has a Mana Pool Cart and a loader :D

**Comment by Prospector** [comment]
Really? Never saw that!

**Comment by SkySom** [comment]
http://botaniamod.net/lexicon.php#poolCart Been there awhile. Was a thing while I was still actively developing Extra carts
