### ISSUE TITLE
Render Overlay Crash Issue in 1.1.0-44

### ISSUE THREAD

**Issue by legendblade** [BrassGoggledCoders/MoarCarts#18]
Null Pointer Exception crash in CartUpdateEvents.renderOverlay when using 1.1.0-44-universal.  There were no MoarCarts carts in the world at the time of the crash, however Railcraft tank carts and locomotive were in visual range.  The crash repeated on reloading the game and logging in to the SP instance again.

[crash-2016-01-16_09.53.27-client.txt](https://github.com/BrassGoggledCoders/MoarCarts/files/92998/crash-2016-01-16_09.53.27-client.txt)

**Comment by SkySom** [comment]
Should be fixed in http://jenkins.k-4u.nl/job/MoarCarts/46/ or you can wait for 1.1.1 to be released on Curse

**Comment by SkySom** [comment]
1.1.1 released with this fixed
