### ISSUE TITLE
IE carts powering Electric Locomotive

### ISSUE THREAD

**Issue by maxhenkes** [BrassGoggledCoders/MoarCarts#20]
Not sure if it's even possibly from outside Railcraft, but it would be lovely to have the IE carts power the electric locomotive similar to how Railcraft carts do it.

**Comment by SkySom** [comment]
Is it possible, yes. Not it make sense? Not particularly. The Electric locos run off Charge/EU, not RF.

**Comment by maxhenkes** [comment]
Why does it not make sense? Charge is simply converted RF or EU most of the time. Railcraft locomotives can already be powered by EU batboxes in carts.

**Comment by maxhenkes** [comment]
Sorry I just realized I had a typo in my first comment which probably made things confusing lol.

Railcraft adds Batbox/MFSU etc in carts by default. Those can power an electric locomotive. I'm just wondering if the same functionality could be added to IE carts.

**Comment by SkySom** [comment]
RF to Charge requires the Flux transformer. The other issue is that none of my carts properly account for drag making them an exceptional good replacement for the EU carts.

**Comment by maxhenkes** [comment]
Yes but EU carts already do this functionality. 

Ah the drag part could be an issue because that's really the only thing thats balancing those carts in Railcraft :(

**Comment by SkySom** [comment]
Right they do. Iirc EU to charge is done automatically in the wires? Could be wrong. But I know for sure RF was established as not being directly charge compatible. Could I eventually add a Flux transformer cart or an rf engine. Yes. And yeah theres some balancing to be done. The diamond chest and the DSU carts drag as much as a vanilla chest cart. Just a little OP

**Comment by maxhenkes** [comment]
Oh I actually don't know for sure. It's been forever since I've used IC2 with Railcraft :P. Charge is basically EU no? That's why RF has to be converted. Tbh the only reason I'm asking is because electrical locomotives aren't that great compared to steam ones and adding the same functionality as those charge carts would make them a bit better. I've always wanted to add that functionality back in because my E-loc can sometimes get stuck.

Tbh there isn't really a need for a flux transformer cart or an RF engine because you can already pump the wires full of RF.
