### ISSUE TITLE
1.8.9-Crash on Startup

### ISSUE THREAD

**Issue by WenXin20** [BrassGoggledCoders/MoarCarts#21]
Crash Log:
http://pastebin.com/AaSpP4X9

**Comment by SkySom** [comment]
Thanks for the Crash log. Is there any way you could also get me the full start up log?

**Comment by WenXin20** [comment]
Ok, I think this is it:
(https://github.com/BrassGoggledCoders/MoarCarts/files/143618/fml-client-latest.txt)

**Comment by SkySom** [comment]
WOops forgot to close this after I fixed last night. Try 2.0.1 should have it fixed.

**Comment by WenXin20** [comment]
Version 2.0.1-10 still crashes

**Comment by SkySom** [comment]
I knew trying to do that right before bed would come to bite me in the ass. Alright. Mind throwing me the startup logs? (Wondering if things properly changed or if it moved old code over) Thanks!

**Comment by WenXin20** [comment]
Ok, here's the crash log: 
(https://github.com/BrassGoggledCoders/MoarCarts/files/145504/crash-2016-02-24_15.58.51-client.txt)
and the startup log:
(https://github.com/BrassGoggledCoders/MoarCarts/files/145506/fml-client-latest.2.txt)

**Comment by LlubNek** [comment]
here's another crash report:
http://pastebin.com/Sgcx8r9x

and latest.log:
http://pastebin.com/dJxZRKgr

fml-client-latest.log is too large for pastebin, but here's the Minecraft launcher's game output:
http://pastebin.com/LcPuVDBR

**Comment by SDUBZ** [comment]
latest log on start up crash https://paste.ee/p/3qP9M

**Comment by SkySom** [comment]
I'm currently testing a fix now. And should get it out a test tomorrow to you guys.

**Comment by SkySom** [comment]
OKAY. Now fixed. For real, this time. Should be approved on Curse soon. Let me know if this works for you guys!

**Comment by WenXin20** [comment]
Yes, it works. :)
