### ISSUE TITLE
Crash w/ Latest MoarCarts & SteamCraft 2

### ISSUE THREAD

**Issue by Sir-Chi** [BrassGoggledCoders/MoarCarts#25]
Hey just to let you know that there is a crash when trying to load the game with MoarCarts 1.2.2, Boilerplate 6.3.0, and SteamCraft2 B5.0.1

If you need any more info just ask :)

thanks in advance, SC

[crash-2016-06-02_16.15.15-client.txt](https://github.com/BrassGoggledCoders/MoarCarts/files/295924/crash-2016-06-02_16.15.15-client.txt)

**Comment by SkySom** [comment]
Yep, this is known. I've alright got https://github.com/BrassGoggledCoders/Steamcraft2/issues/367 for it now. Steamcraft doesn't use the new boilerplate yet. Just roll back to old MoarCarts/Boilerplate for now. Should have a release in the next few days to fix this.

**Comment by Sir-Chi** [comment]
Ah thanks for the heads-up :) Much appreciated, I'll do that then.
