### ISSUE TITLE
[1.7.10] IE Barrel cart bug, and question

### ISSUE THREAD

**Issue by KryptonCaptain** [BrassGoggledCoders/MoarCarts#29]
Right-clicking on the barrel cart with a bucket wiped my inventory except for the bucket I got back. Just a bit of a problem

Also, how does the comparator rail work? And will we see any other cart types added to 1.7 version, like the potential ender IO capacitor carts I saw on the old extra carts git

**Comment by SkySom** [comment]
Oh shit. I will take a look ASAP. Also the comparator rail works like any other block that works with comparators, it'll output a signal based on what block is in the cart.

**Comment by KryptonCaptain** [comment]
I'm not sure the comparator track is working either. I'm getting max signal strength no matter what cart type, or what's in the cart. 
It also doesn't have a recipe.

**Comment by SkySom** [comment]
I ummm it should... A redstone torch and a detector track.

**Comment by SkySom** [comment]
Are you sure you have the newest version?

**Comment by KryptonCaptain** [comment]
I'm using the latest one on curse - 1.2.3-8. So short of building it from the source, I'm pretty sure that's the most recent one

**Comment by SkySom** [comment]
Alright. Thank you for the information. I will take a look as soon as I get a moment!

**Comment by KryptonCaptain** [comment]
Any news on a fix for this?

**Comment by SkySom** [comment]
No sorry. Life got very hectic, but I will take another look this evening. Should be able to at least release a version that has the recipe, and interact with the carts turned off (So that it won't do this, and the only way to interact will to use the fluid loaders

**Comment by SkySom** [comment]
Fixed. New Version on Curse.
